<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span></div>

# Storing Data (Good) Exercises
## Exercise 1 (Total recall) 
|    Term    |       Brief description       |
|:----------:|:-----------------------------:|
| Subsetting | Making a selection            |
| Indexing   | To select one element         |
| Slicing    | To select a range of elements |
| Masking    | Selecting entries in arrays   |

## Exercise 2 (Show me the ‘odd’ letters)


In [ ]:
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])
masked_array = np_array_2d[:,0]                         # Selects all elements in the first position
masked_array = masked_array.astype(int) % 2 == 1        # Converts the elements to integers, get the remainder when element is divided by 2, check if remainder is equal to one
masked_array = np_array_2d[masked_array]    # Apply mask
masked_array = masked_array[:,1]
print(masked_array)

['A' 'C' 'E' 'G' 'I']


## Exercise 3

In [ ]:
array = np.array([[66, 50, 57, -1, -1],
 [92, -1, 88, -1, -1],
 [75, -1, -1, 76, -1],
 [-1, 51, 87, -1, -1],
 [71, -1, 67, -1, 69]])
for i in range(0,5):
    for j in range(0,5):
        if array[i,j] < 50:
            array[i,j] = -1
        if array[i,j] > 50:
            array[i,j] = 1
        if array[i,j] == 50:
            array[i,j] = 0
print(array)

[[ 1  0  1 -1 -1]
 [ 1 -1  1 -1 -1]
 [ 1 -1 -1  1 -1]
 [-1  1  1 -1 -1]
 [ 1 -1  1 -1  1]]


In [ ]:
array = np.array([[66, 50, 57, -1, -1],
 [92, -1, 88, -1, -1],
 [75, -1, -1, 76, -1],
 [-1, 51, 87, -1, -1],
 [71, -1, 67, -1, 69]])
array[(array < 50)] = -1    # Replace all elements less than 50 with -1
array[(array > 50)] = 1     # Replace all elements greater than 50 with 1
array[(array == 50)] = 0    # Replace all elements equal to 50 with 0
print(array)

[[ 1  0  1 -1 -1]
 [ 1 -1  1 -1 -1]
 [ 1 -1 -1  1 -1]
 [-1  1  1 -1 -1]
 [ 1 -1  1 -1  1]]
