<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

## 1 Lists, Arrays & Dictionaries
### 1.1 Let's compare
There are three ways to store data in Python: lists, NumPy arrays and dictionaries 

**Python Lists**
```python 
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]
```

**Numpy Arrays**
```python
import numpy as np
np_super_names = np.array(["Black Widow", "Iron Man", "Doctor Strange"])
np_real_names = np.array(["Natasha Romanoff", "Tony Stark", "Stephen Strange"])
```

**Dictionary**
```python
superhero_info = {
    "Natasha Romanoff": "Black Widow",
    "Tony Stark": "Iron Man",
    "Stephen Strange": "Doctor Strange"
}
```
Notice:
- Dictionaries use a key and an associated value separated by a :
- The dictionary very elegantly holds the real and superhero names in one structure while we need two lists (or arrays) for the same data.
- For lists and arrays, the order matters. I.e. ‘Iron Man’ must be in the same position as ‘Tony Stark’ for things to work.

### 1.2 Accessing data from a list (or array)
To access data from lists, we need to use an index corresponding to the data's position. A reminder that Python starts counting from 0.

In [10]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

print(py_real_names[0]) # Prints first element in the list
print(py_super_names[0])

Natasha Romanoff
Black Widow


We can use a negative index to count from the back of the list. For example, [-1] will give the last element, [-2], the second last and so on. 

This is useful as we can access the last element without knowing how many elements there in a list.

In [11]:
print(py_super_names[2])       # Forward indexing
print(py_super_names[-1])      # Reverse indexing 

Doctor Strange
Doctor Strange


### 1.3 Accessing data from a dictionary
Dictionaries hold data value paired with a key. This means you can access the data value (e.g. the superhero name) using the assigned name as a key.

In [12]:
superhero_info = {
    "Natasha Romanoff": "Black Widow",
    "Tony Stark": "Iron Man",
    "Stephen Strange": "Doctor Strange"
}                  
superhero_info["Natasha Romanoff"]

'Black Widow'

To access keys, use .keys(). 
To access values use .values()

### 1.4 Higher dimensional lists
Unlike with a dictionary, we needed two lists to store the real and corresponding superhero names. We can also represent the information as a 2D array.
```python
py_superhero_info = [['Natasha Romanoff', 'Black Widow'],
                     ['Tony Stark', 'Iron Man'],
                     ['Stephen Strange', 'Doctor Strange']]
```

## 2   Lists vs Arrays
### 2.1 Size
To find how many elements there are in a list/array, you can use len(). For arrays however, there are other options too.

In [13]:
import numpy as np
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)

print(len(py_list_2d))
print(len(np_array_2d))
print(np_array_2d.shape) #Gives both number of elements and dimension

10
10
(10, 2)


### 2.2 Arrays are fussy about type
One prominent difference between lists and arrays is that arrays insist on having only a single data type, whereas lists do not.

In [14]:
py_list = [1, 1.5, 'A']
np_array = np.array(py_list)

In [15]:
py_list

[1, 1.5, 'A']

In [16]:
np_array

array(['1', '1.5', 'A'], dtype='<U32')

### 2.3 Adding a number
Adding a number to an array adds that number to every element in the array. This does not work for lists.

In [17]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)  

np_array + 10

array([11, 12, 13, 14, 15])

In [18]:
py_list + 10 # This will not work

TypeError: can only concatenate list (not "int") to list

### 2.4 Adding another list
To combine two lists or two arrays together, use +

In [ ]:
py_list_1 = [1, 2, 3, 4, 5]
py_list_2 = [10, 20, 30, 40, 50]

np_array_1 = np.array(py_list_1)
np_array_2 = np.array(py_list_2)

In [ ]:
py_list_1 + py_list_2

[1, 2, 3, 4, 5, 10, 20, 30, 40, 50]

In [ ]:
np_array_1 + np_array_2

array([11, 22, 33, 44, 55])

### 2.5 Multiplying by a Number
Multiplying a list repeats the list n times. \
Multiplying an array multplies the individual elements in the array by x.

In [ ]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

In [ ]:
py_list*2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [ ]:
np_array*2

array([ 2,  4,  6,  8, 10])

### 2.6 Squaring

In [ ]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

np_array**2

array([ 1,  4,  9, 16, 25])

In [ ]:
py_list**2      # Won't work!  

### 2.7 Asking questions

In [ ]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

In [ ]:
py_list == 1    # Works, but what IS the question?

False

In [ ]:
py_list == [1, 2, 3, 4, 5]  # Tests if py_list is equal to another list

True

In [ ]:
py_list > 3      # Won't work!

In [ ]:
np_array == 3   # Tests if element is = 3

array([False, False,  True, False, False])

In [ ]:
np_array > 3    # Tests if element is > 3

array([False, False, False,  True,  True])

### 2.8 Mathematics

In [ ]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)        

In [19]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

sum(py_list)     # sum() is a base Python function
max(py_list)     # max() is a base Python function
min(py_list)     # min() is a base Python function
np_array.sum()
np_array.max()
np_array.min()
np_array.mean()
np_array.std()

1.4142135623730951