<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

## 1 Subsetting: Indexing and Slicing
- Subsetting means to 'select'
- Indexing refers to select one element
- Slicing refers to selecting a range of elements

Often, we need to select a subset of the data in a list (the set). One way to do this is through indexing, i.e. list[0] takes the first element from the list 'list'. Another option is to select a range of elements. This is called slicing.

### Lists & Arrays in 1D | Subsetting & Indexing
To slice a list, we must specify two indices to indicate the start and end of the slice.

In [22]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

py_list=["a1", "b2", "c3", "d4", "e5",
         "f6", "g7", "h8", "i9", "j10"]
np_array=np.array(py_list)

# Same syntax for both lists and arrays
x = py_list  
y = np_array

x[0:3] # Index 1 to 2
x[1:6] # Index 1 to 5
x[1:6:2] # Index 1 to 5, skips every 2nd element
x[5:] # Index 5 to the end
x[:5] # Index 0 to 5
x[5:2:-1] # Index 5 to 3, in reverse
x[::-1] # Reverses the list



NameError: name 'np' is not defined

## 1.2 Arraus only | Subsetting by masking
Using NumPy arrays, we can select elements that meet a certain condition.

In [ ]:
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
my_mask = np_array > 3 # Checks which elements are greater than 3
my_mask

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

We can ask NumPy to show only those that are True i.e. greater than 3 by

In [ ]:
np_array[my_mask]

array([ 4,  5,  6,  7,  8,  9, 10])

To invert our mask, i.e. find elements less than 3, we can use '~', the Bitwise Not operator.

In [ ]:
np_array[~(np_array > 3)]
np_array[(np_array <= 3)]   

array([1, 2, 3])

array([1, 2, 3])

To combine two masks together, we can use '&', the Bitwise AND operator. This will give the elements that satisfy all of the conditions listed.

In [ ]:
np_array[(np_array > 3) & (np_array < 8)]

array([4, 5, 6, 7])

We can also find the elements that satisfy none of the conditions listed. We do this through '|', the Bitwise OR operator.

In [ ]:
np_array[(np_array < 3) | (np_array > 8)]

array([ 1,  2,  9, 10])

## 1.3 Lists & Arrays in 2D | Indexing & Slicing

In [ ]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)

In [ ]:
py_list_2d[3]
np_array_2d[3]

[4, 'D']

array(['4', 'D'], dtype='<U21')

To select an element in a 2D list, two square brackets i.e. [a][b] must be used. \
To select an element in a 2D array, one square bracket, with a comma [a,b] is used instead.

In [ ]:
py_list_2d[3][0]
np_array_2d[3, 0] 

4

'4'

In [ ]:
py_list_2d[:3]
np_array_2d[:3]

[[1, 'A'], [2, 'B'], [3, 'C']]

array([['1', 'A'],
       ['2', 'B'],
       ['3', 'C']], dtype='<U21')

```python
list[:a][b]
```
The first square bracket slices the list. In the following examples, we have selected the first a elements e.g. [:2] includes the 1st and 2nd elements. \
The second square bracket selects the b-th element within the slice.

To display all elements within the list/array, just write [:] in the first bracket.


In [ ]:
py_list_2d[:2][0]   # Within the first two elements, select the 1st element
print("---")
py_list_2d[:2][1]   # Within the first two elements, select the 2nd element 
py_list_2d[:3][2]   # Within the first three elements, select the 3rd element
print("---")
py_list_2d[3:6][0]  # From element 4 to 5, select the 1st element
py_list_2d[3:6][1]  # From element 4 to select the 2nd element
print("---")
py_list_2d[3:6][0]
np_array_2d[3:6, 0]
np_array_2d[:, 0]

[1, 'A']

---


[2, 'B']

[3, 'C']

---


[4, 'D']

[5, 'E']

---


[4, 'D']

array(['4', '5', '6'], dtype='<U21')

array(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'], dtype='<U21')

## 1.4 Growing lists
### Example 1
    Creating a larger list from a smaller one
```python
x=[1, 2]*5 # replicates the elements 1,2 in the array 5 times.
x
```
```python
[1, 2, 1, 2, 1, 2, 1, 2, 1, 2]
```
### Example 2 
    Three ways to grow a list by appending one element at a time.
```python
x=[1]
x= x + [2]
x= x + [3]
x= x + [4]

x=[1]
x+= [2]
x+= [3]
x+= [4]

x=[1]
x.append(2)
x.append(3)
x.append(4)
```
All of these forms are equivalent, and give the same output:
```python
[1, 2, 3, 4]
```
### Example 3
    Here are three ways of incorporating multiple elements.
```python
x = [1, 2, 3]
x += [4, 5, 6]
```
```python
x=[1, 2, 3]
x.extend([4, 5, 6])
```
Both of these give you the same output:
```python
[1, 2, 3, 4]
```
If you want to append a list onto another list, i.e. making the whole of list A, an element of list B:
```python
x=[1, 2, 3]
x.append([4, 5, 6])
```

## 1.5 Tuples
Tuples are similar to lists, but use round brackets instead of square brackets. Tuples also cannot be changed after creation (i.e. they are immutable).

In [ ]:
a=(1, 2, 3)     # Define the tuple
print(a[0])     # Access data
# The following will NOT work
a[0]=-1
a[0]+= [10]

1


TypeError: 'tuple' object does not support item assignment

## 1.6 Be VERY careful when copying
You should be particularly mindful when making copies of lists and arrays as some unexpected errors may pop up due to the quirks of Python. 

For example, if you want to copy a list, do not do the following:
```python
x=[1, 2, 3]
y=x           # DON'T do this!
z=x           # DON'T do this!
```
Do this instead:
```python
x=[1, 2, 3]
y=x.copy()
z=x.copy()
```